version: "3.7"

services:

  react:
    image: nodebokeh
    build:
      context: react-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"

  bokeh:
    image: rokeh
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "5010:5010"
    volumes:
      - "./data:/home/python/code/data"
      - "./code:/home/python/code"
    depends_on:
      - react
